### ISSUE TITLE
Windows wrapper please

### ISSUE THREAD

**Issue by retsa** [Sakartu/sicksubs#12]
Some of us windows users would greatly appreciate a wrapper. Thanks a bunch. :)

**Comment by Sakartu** [comment]
The windows wrapper was supposed to fix the lack of cron on windows, for windows users. The same functionality as cron, however, can be realized using Windows Tasks: for more information take a look at [this](http://support.microsoft.com/kb/226795) article for instance. One could create a task to run on logon, which should run 
`C:/path/to/python C:/path/to/sicksubs.py` every hour. A full guide can be found [here](http://www.howtogeek.com/120566/how-to-create-a-repeating-alarm-in-windows-7-without-extra-software/)

Does this fix your issue, or should I provide a proper wrapper?

**Comment by retsa** [comment]
I'll test it. In the mean time, I'm attaching a pastebin of an errornous run of test.py. I dont know if it works yet, but I figured it might be valuble for you:
http://pastebin.com/mfRK0N6L

**Comment by Sakartu** [comment]
Ah, yes, I have written the tests for a linux-only environment, so they
won't work on Windows. Furthermore, they haven't been maintained as well as
the rest of the code, so even under linux at least one of the testcases
fails. It's not a really widespread used piece of software though, so I
think I'll leave it like this.

Let me know how the testing turns out, so I can provide assistance if
needed.

**Comment by Sakartu** [comment]
Is there any progress on testing the supplied solution? If not, I think I have a Windows wrapper ready, but it may need some testing...

**Comment by retsa** [comment]
I tried a few times to solve the issue about passing arguments through the batch file with no success and gave up on it. I'd be more than happy to test your wrapper.
