### ISSUE TITLE
sicksub & Sickbeard + remote location

### ISSUE THREAD

**Issue by aroundmyroom** [Sakartu/sicksubs#9]
I'm checking out several scripts which I might be using for bierdopje. (I am using now 2 scripts where 1 is having big potential but is missing a notifier. My request is following:

My sickbeard is running remotely on a webserver attached to the internet outside of my local network. Can I use this script when I use it in combination with sickbeard but all my downloaded subs are on a NAS in my local network downloaded by sabnzbd?

**Comment by Sakartu** [comment]
I saw you're Dutch (so am I), but let's keep it English so other people may read this as well :).

Does your sickbeard perform postprocessing for you? Because that is something that sicksubs requires, as it uses a hook in the post processing routines. Sicksubs is actually called by sickbeard with a set of arguments based on which sicksubs can find and download subtitles. If it does post processing for you then sicksubs should work without problems.

If it doesn't, maybe I could provide a simple commandline argument (something like --find_subs /media/media/series/) which makes sicksubs look through your series directory recursively and find subs for each of the shows? That way you could just run it in a crontab on your sabnzbd machine in your local network without the need to communicate with sickbeard altogether. 

Mind you, as sicksubs works fine for my setup fixing this bug might take a while, especially since I'm in the middle of moving from one house to another, but leaving the issue open can never hurt.

**Comment by aroundmyroom** [comment]
My Situation is following

Sickbeard is installed at http://sickbeard.domain.com
it's checking the TV series, when valid it will check the nzb from the sources (nzbmatrix, sickbeard etc.)
than through the API it sends the request to sabnzbd which than retrieves the nzb from the source.

Sabnzbd however is located at a plugcomputer device in my local network reachable through http://home.domain2.com which has no relation with Sickbeard.

Sickbeard is running soley to offer the TV info / and  info for me.

Meanwhile I am using a script from sourceforge (bierdopje0.2 or something) which is downloading 90% of the TV series (I have around 120 TV series in my folder (Yes mainly all series I have watched .... ) ;-)

the other script with potential is: http://code.google.com/p/auto-sub
missing is a postprocessing here (unde dev.) where I can hook my twitter info to so that I can see that actually subs have been downloaded.

So I am looking for alternatives ;-)

So your alternative is a way to do. the auto-sub is good, but dev is slow ;-)

**Comment by Sakartu** [comment]
Hey aroundmyroom,

I'm afraid your situation isn't supported by sicksubs. The problem is that sicksubs is called as a post-post-processing script (through the extra_scripts directive in the sickbeard.ini file) and there isn't really any other way of calling sicksubs easily. 

The calling convention for sicksubs is found on https://code.google.com/p/sickbeard/wiki/AdvancedSettings under the Extra Scripts section. You could jerry rig the call using cron but this leaves the problem that sicksubs needs the tvdbid of a show to download subs for it and these can't be found in the name of an ep; sickbeard does provide this information when calling extra scripts.

I'm sorry I couldn't be of more help. Good luck in your hunt!
